#!/usr/bin/bash

wget -O libsodium.tar https://download.libsodium.org/libsodium/releases/libsodium-1.0.21-stable.tar.gz
tar -xf ./libsodium.tar
cd ./libsodium-stable
./configure
make check && make
sudo make install

cd ../../
rm -rf ./libsodium-stable
rm -rf ./libsodium.tar